/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package groupon;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author aks
 */
public class GroupOn extends javax.swing.JFrame {

    /**
     * Creates new form Initialising
     */
    public GroupOn() {
        initComponents();
        displayLabel.setText("Initialising GroupOn.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        displayLabel.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        displayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try
        {
            displayLabel.setText("Initialising GroupOn.");
            Thread.sleep(1000);
            String username="";
            File f=new File(System.getProperty("user.home")+"/GroupOn/resumeSession.txt");
            if(f.exists())
            {
                int flag=0;int flag2=0;
                displayLabel.setText("Initialising GroupOn..");
                Thread.sleep(500);
                System.out.println("In here");
                BufferedReader br=new BufferedReader(new FileReader(System.getProperty("user.home")+"/GroupOn/resumeSession.txt"));
                if((username=br.readLine())!=null)
                {
                    
                    System.out.println("In here 2");
                    int option = JOptionPane.showConfirmDialog(null, "Session of"+username+"Recovered\nDo you want to resume offline ?", "GroupOn", JOptionPane.YES_NO_OPTION);
                    System.out.println(""+option);
                    if(option==0)
                    {
                        flag=1;
                        // Open Messenger
                        displayLabel.setText("Initialising GroupOn...");
                        Thread.sleep(500);
                        Messenger.isOnline=false;
                        Messenger msg=new Messenger(null, username);
                        msg.setVisible(true);
                        this.dispose();
                    }
                    else
                    {
                        flag2=1;
                        new FileWriter(System.getProperty("user.home")+"/GroupOn/resumeSession.txt");
                        Thread.sleep(500);
                        Welcome wel=new Welcome();
                        wel.setVisible(true);
                        this.dispose();
                    }
                }
                if(flag==0 && flag2==0)
                {
                    Welcome wel=new Welcome();
                    wel.setVisible(true);
                    this.dispose();
                }
            }
            else
            {
                displayLabel.setText("Initialising GroupOn..");
                Thread.sleep(500);
                System.out.println("In here 3");
                if(!(new File(System.getProperty("user.home")+"/GroupOn").exists()))
                    new File(System.getProperty("user.home")+"/GroupOn").mkdir();
                
                new FileWriter(System.getProperty("user.home")+"/GroupOn/resumeSession.txt");
                
                displayLabel.setText("Initialising GroupOn...");
                Welcome wel=new Welcome();
                wel.setVisible(true);
                this.dispose();
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GroupOn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GroupOn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GroupOn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GroupOn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GroupOn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel displayLabel;
    // End of variables declaration//GEN-END:variables
}
